### ISSUE TITLE
BP_Test_Actor Mislabeled Limbs 

### ISSUE THREAD

**Issue by torinmb** [secretlocation/azure-kinect-unreal#10]
When running the BP_Test_Actor it looks like you're only accounting for 25 out of the 31 limbs, so all the labels are thrown off when displayed on a person.

Looks like Left Thumb, Left Hand, Left Hand Tip,  Right Thumb, Right Hand, Right Hand Tip are missing.

**Comment by dylandevs** [comment]
Yep, confirmed! We didn't add the new joints in the test actor from the new SDK version.
