### ISSUE TITLE
anyway to  just use the kinect as a virtual camera with this?

### ISSUE THREAD

**Issue by zeoezone** [secretlocation/azure-kinect-unreal#11]
i know you can use an I pad to do it, so it gotta be possible with the azure kinect

**Comment by torinmb** [comment]
it looks like the Kinect joints are exposed but not the video feed. It'd be great to be able to get the Ir, webcam, or point cloud data. This would open up a lot of possibilities

**Comment by MrPantherM** [comment]
Yes please - point cloud data into Unreal with a Kinect is a must

**Comment by dylandevs** [comment]
Hey y'all,
We're planning on adding video feed support for sure, but it's just body tracking right now!

**Comment by MrPantherM** [comment]
Seriously - it’s what everyone has been waiting for! Looking forward to
testing it out!

PM
